services:
  - type: web
    name: spm-api
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./apps/api/Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: DEVICE_TOKEN
        sync: false
      - key: MQTT_URL
        sync: false
      - key: MQTT_USERNAME
        sync: false
      - key: MQTT_PASSWORD
        sync: false
      - key: SEED_ADMIN_EMAIL
        sync: false
      - key: SEED_ADMIN_PASSWORD
        sync: false